<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <DefaultItemExcludes>$(DefaultItemExcludes);SpinnerApp\**;Spinner.cs</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniExcel" Version="1.45.0" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SpinnerApp\2026-여름방학_기자제 (노트북(HP OMEN 게이밍 노트북) 대여 현황서양식.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="SpinnerApp\2026-여름방학_기자제 (노트북(HP OMEN 게이밍 노트북) 대여 현황서양식 - 복사본.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>